defaults: &defaults
  host: localhost

development:
  <<: *defaults
  database: smshare_development

test:
  <<: *defaults
  database: smshare_test

production:
  <<: *defaults
  username: smshare
  password: 482D4DE1-72A8-4CA3-9265-C4EA72E2C957
  database: smshare_production