defaults: &defaults
  host: localhost

development:
  <<: *defaults
  database: smshare_development

test:
  <<: *defaults
  database: smshare_test

production:
  <<: *defaults
  username: smshare
  password: ahoy_and_avast
  database: smshare_production
