# Here you can specify default options for TinyMCE across all controllers
#
theme: advanced
theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_buttons1_add:
  - fontselect
  - fontsizeselect
  - forecolor
  - separator
  - bold
  - italic
  - underline
  - strikethrough
  - separator
  - justifyleft
  - justifycenter
  - justifyright
  - justifyfull
  - separator
  - code
plugins:
  - contextmenu
  - paste
